export enum POST_ACTIONS {
  GET_ALL_POSTS = 'GET_ALL_POSTS',
  GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS',
  GET_ALL_POSTS_START = 'GET_ALL_POSTS_START',
  GET_ALL_POSTS_ERROR = 'GET_ALL_POSTS_ERROR',

  ADD_LIKE = 'ADD_LIKE',
  ADD_LIKE_SUCCESS = 'ADD_LIKE_SUCCESS',
  ADD_LIKE_START = 'ADD_LIKE_START',
  ADD_LIKE_ERROR = 'ADD_LIKE_ERROR',

  ADD_COMMENT = 'ADD_COMMENT',
}
